### ISSUE TITLE
Magnum support

### ISSUE THREAD

**Issue by eugenetaranov** [gophercloud/gophercloud#1003]
Hello,

is magnum api considered stable now? I'd like to cleanup/update where appropriate magnum related code and get it merged.

**Comment by ozerovandrei** [comment]
+1 to that question.

Gophercloud doesn't have support for the `clusters`, `cluster templates` and `quotas`.
And `bays` and `baymodels` are deprecated names now: [ocata release notes](https://docs.openstack.org/releasenotes/magnum-ui/ocata.html#prelude).

Also Magnum uses `Container infrastructure management` term for its service name instead of the `Container orchestration`.

**Comment by jtopjian** [comment]
No doubt a good amount of updates are needed in the magnum branch. I think the best way forward is for someone to audit it to see what's still relevant and begin copying it to the master branch in small pieces. Usual Gophercloud rules apply.

I can certainly add this to my list of items, but that list is really long right now :smile:

**Comment by eugenetaranov** [comment]
thanks @jtopjian for confirmation, will work on this next weeks

**Comment by JackKuei** [comment]
@jtopjian @eugenetaranov Will have some bandwidth to contribute to this project as well. See how we can work together on this.

**Comment by mrhillsman** [comment]
@jtopjian @eugenetaranov @JackKuei @ozerovandrei if any of you could use a development server to work on OpenLab would be glad to assist. Please just fill out "Get Started" form at https://openlabtesting.org

**Comment by openstacker** [comment]
@eugenetaranov @jtopjian I'm active contributor for OpenStack Magnum now and I'm happy to work with you guys together. The long term goal is supporting Magnum in Terraform ;) thanks.

**Comment by jtopjian** [comment]
@mrhillsman 

> if any of you could use a development server to work on OpenLab would be glad to assist.

We're looking to deploy Magnum at `$work` so I should have a magnum environment available soon. If someone gets started before me (which is the most likely possibility), that'll at least help with verifying PRs.

If we could have a CI job for Magnum, that would really help!

@openstacker 

> I'm active contributor for OpenStack Magnum now and I'm happy to work with you guys together.

Thanks! Once work gets started, I might ping you if any questions about the API come up.

> The long term goal is supporting Magnum in Terraform

That would be a welcomed addition, too. Adding support to Gophercloud is the first step and then I can assist with the Terraform side, too.

If anyone begins working on this, as I mentioned before: usual Gophercloud rules apply. We recently added a [contributor's tutorial](https://github.com/gophercloud/gophercloud/tree/master/docs/contributor-tutorial) which details the whole process.

I used to use the [Identity v3](https://github.com/gophercloud/gophercloud/tree/master/openstack/identity/v3) packages as the best set of packages to use as templates. This is still true, though I would also encourage taking a look at the [Messaging v2 PRs](https://github.com/gophercloud/gophercloud/pulls?q=is%3Apr+messaging).

**Comment by openstacker** [comment]
@jtopjian Thanks for the quick response. And I'm happy to answer questions about Messaging (Zaqar), I was PTL for Zaqar for many cycles. Just FYI.

**Comment by JackKuei** [comment]
@jtopjian @openstacker Using gophercloud for terraform is our goal as well. Looking forward to work with you. We had some problems using zaqar with senlin, now I know who to contact. :)

**Comment by JackKuei** [comment]
Going to start with Manage Cluster Template first. 
[https://developer.openstack.org/api-ref/container-infrastructure-management/](url)
---
- [ ] Manage Cluster Templates: Create
- [ ] Manage Cluster Templates: List
- [ ] Manage Cluster Templates: Get
- [ ] Manage Cluster Templates: Update
- [ ] Manage Cluster Templates: Delete
---

**Comment by openstacker** [comment]
@JackKuei Would you mind starting with cluster first? I already got patches for Cluster Template, which will be submitted today or tomorrow. Thanks.

**Comment by openstacker** [comment]
@JackKuei You can refer my branch (https://github.com/openstacker/gophercloud/tree/magnum-support) for the /cluster CRUD work. It's mostly renamed from the old magnum branch. The other resource we need to do is the /certificates. You can take it if you want.

BTW, I'm also working on the magnum support for shade (https://review.openstack.org/577342) and ansible. Welcome to join if you're interested in. Cheers.

**Comment by JackKuei** [comment]
@openstacker Seems like we are duplicating efforts. Had to start on clustertemplates since it is required for clusters. Saw some gaps between your and mine clustertemplates, we can reconcile later

**Comment by eugenetaranov** [comment]
@JackKuei @openstacker clustertemplates/clusters/certificates CRUD and tests are already completed by me just did not push PR yet :) https://github.com/eugenetaranov/gophercloud/tree/magnum-clusters/openstack/containerorchestration/v1 let's sync on the work being done so it's not duplicated

**Comment by openstacker** [comment]
@eugenetaranov If that's the case, feel free submit your patches and I'm happy to review them from the Magnum PoV.

@JackKuei @eugenetaranov I'm happy to abandon my commits and review you guys commits. Please submit them. Thanks.

**Comment by JackKuei** [comment]
@eugenetaranov Took a quick glance of your code, there are some discrepancies between your and my codes. I've created a PR issue to track the Magnum merging effort. #1062. I'll create PRs for the clustertemplates shortly then we can discuss.

**Comment by jtopjian** [comment]
I _really_ appreciate the effort the three of you are putting into this. I agree with @JackKuei that someone submitting a PR and everyone reviewing is the best way way to go. Please let me know if I can assist, otherwise I'll let you folks coordinate.

One thing to note is that someone can submit a PR to the other person's branch and Github will automatically reflect the updates. For example, if @JackKuei submits a PR and either @eugenetaranov or @openstacker want to submit a fix, then open a PR to https://github.com/JackKuei/gophercloud on his branch and merge it. This might help with collaboration across all interested parties.

Once everything looks good, I can give the `gophercloud/gophercloud` PR a review and merge.

Another thing to note is that I just added a package template to https://github.com/gophercloud/gophercloud/tree/master/docs/contributor-tutorial/.template which might help conforming to the style guidelines I made in #1061. I recommend picking an action (list, create, get, etc) and removing the _other_ actions from the template. Once you finish one action, open a PR, then create a new branch based off of the previous branch, and add in the next action.

I also recommend using updated fixtures than what is in the current `magnum` branch. Fixtures are really easy to generate by using `openstack --debug`. For example:

```
openstack --debug coe cluster template list
```

I copy the JSON response to a text file and then do:

```
python -mjson.tool tmp.json
```

This goes right in `fixtures.go` as an up-to-date fixture :)

**Comment by openstacker** [comment]
@jtopjian All good suggestions. Thanks a lot. And yes, it's really excited to see contributions for gophercloud from different parties which means this is a very active community. 

@eugenetaranov I reviewed your code quickly seems your haven't done the acceptance work. But for my commits, I'm pretty sure the acceptance tests can pass. So I would suggest you and @JackKuei  can focus on the /clusters, /certificates, /services, /stats and /quotas. And I can focus on the /clustertemplates CREATE if you guys do think it's a blocker.

Besides, I would like to highlight that this is not just a renaming work, it's involving a bunch of changes  how the service works.

We can have a quick sync up on slack at the #sig-openstack channel, kubernetes workspace. My slack ID is **flwang**. Cheers.

**Comment by openstacker** [comment]
@JackKuei As I mentioned above, seems @eugenetaranov 's code missing test so I would suggest just reuse my code because I have done a lot of effort on the test part. I will submit a patch for cluster templates CREATE and LIST quickly. And actually, I don't think there is a block for the testing for cluster, because you can manually create the template in your devstack and just refer the ID when creating clusters.

**Comment by jtopjian** [comment]
> I would like to highlight that this is not just a renaming work, it's involving a bunch of changes how the service works.

Yes :)

> And actually, I don't think there is a block for the testing for cluster, because you can manually create the template in your devstack and just refer the ID when creating clusters.

Yes, this is a good idea. Once more things are merged, the hard-coded UUIDs can be removed and leverage other acceptance test code.

**Comment by JackKuei** [comment]
@openstacker I started clustertemplates because didn't know you or eugenetaranov had already started, and I even posted in here. As such I'm basically done all the work including unit test and acceptance test hitting against a live system for clustertemplates. Will open PRs tomorrow. My quick glance of your code earlier today had some discrepancies with mine. We can discuss more tomorrow once we start to merge our codes.

**Comment by eugenetaranov** [comment]
@mrhillsman thanks for invitation, I applied a week ago but heard no response since then...  if you could assist that would be really great as I do not have access to openstack atm

**Comment by ozerovandrei** [comment]
@JackKuei, @openstacker, @eugenetaranov 

Hi guys, do you mind if I help you with Magnum?
It seems that Templates, Clusters and Certificates API are currently being developed, as I see in #1062.

Has anyone started implementing Quotas API? Can I grab it?

**Comment by ozerovandrei** [comment]
@JackKuei that looks great already! I better not to interfere with it 😅

**Comment by JackKuei** [comment]
@ozerovandrei Haven't had time to exercise it yet. But if you want to do the terraform-provider-openstack and exercise it at the same time it would be even better. I haven't started on the terraform-provider-openstack for magnum yet.

**Comment by jtopjian** [comment]
I think we need to wait on a few more PRs in Gophercloud before work in Terraform is possible (or even productive).

**Comment by ozerovandrei** [comment]
Yeah, I think we need at least full Cluster Templates or Clusters support in the Gophercloud to start implementing it in the Terraform provider.

**Comment by jtopjian** [comment]
I'm going to close this in favor of #1062
