### ISSUE TITLE
Auth from env: OS_TOKEN support

### ISSUE THREAD

**Issue by ozerovandrei** [gophercloud/gophercloud#1005]
Hello.

Right now Gophercloud doesn't support `OS_TOKEN` or `OS_AUTH_TOKEN` environment variable for `AuthOptionsFromEnv()` function.
Some of the projects that uses Gophercloud implemented this feature by itself: [terraform-provider-openstack#6081](https://github.com/hashicorp/terraform/pull/6081)

Is this a recommended way to deal with lack of `OS_TOKEN` environment variable support?

If not, can we implement it? It seems really easy to do, and I linked a PR for this issue.

Documentation (wiki) reference: https://wiki.openstack.org/wiki/OpenStackClient/Authentication
Code references are provided in the linked PR.

**Comment by jtopjian** [comment]
At the moment I'm not keen to add further support to `AuthOptionsFromEnv`. I think it serves a basic purpose for use in testing and development, but I would prefer users to use `gophercloud/utils/clientconfig` for anything beyond testing.

**Comment by ozerovandrei** [comment]
@jtopjian oh I see.
So, right now the most recommended way for external packages to build `AuthOptions` from yaml or env variables is to use [clientconfig/AuthOptions](https://github.com/gophercloud/utils/blob/master/openstack/clientconfig/requests.go#L119)?

**Comment by jtopjian** [comment]
@ozerovandrei correct :)

The key here is "external packages" - I'd like for applications which consume Gophercloud to start using `clientconfig` for authentication since that package will support all authentication options users/devs expect to see.

Granted, unless someone has browsed some existing issues here, they would not be aware of `clientconfig`. At some point I hope to get that documented soon.

**Comment by ozerovandrei** [comment]
@jtopjian thank you for the clarification.

Yeah, some tips in documentation would be helpful.
Closing this issue then.
