### ISSUE TITLE
Add support for instance tags.

### ISSUE THREAD

**Issue by gislifreyr** [gophercloud/gophercloud#1093]
The OpenStack compute API supports tagging instances since microversion 2.26 and since microversion 2.52 [supports adding tags at creation time](https://developer.openstack.org/api-ref/compute/#create-server).

It would be great if gophercloud could add support for these features. I imagine this would be two separate features:

1. Adding support to tag instances on creation.
2. Adding support to edit tags for already running instances.

My Go programming experience is on a beginner's level but I'd be willing to give it a shot. I at least have some idea how to implement feature no. 1 after reading the relevent source code.

**Comment by jtopjian** [comment]
@gislifreyr Gophercloud doesn't have official support for microversions yet. There have been a handful of microversion features that have been merged, but sort of in an unofficial/unsupported capacity.

I would be OK with adding this as long as it doesn't break behavior for clients that don't set a microversion. I imagine this is as simple as ensuring `tags` aren't included in the body unless they're specified (which is usually the default for `[]string` fields).

I'm a little hesitant to add support for `Tags` to the server's result, though, since that would be visible to all clients and might confuse those who don't have access to the required microversioned results.

If you're OK with that, give it a shot. It can also serve as a way for me to experiment with microversions with the compute service.

Two PRs would be the best way to go. Our [contributor tutorial](https://github.com/gophercloud/gophercloud/tree/master/docs/contributor-tutorial) has a good amount of information to get started. Let me know if you have any questions. :)

**Comment by jtopjian** [comment]
@gislifreyr If you don't mind, I'm going to work on this. I have an idea for a microversion implementation that I want to test with it.

**Comment by gislifreyr** [comment]
Just got back from vacation...
Glad to see that there has been some work done :+1:

**Comment by jtopjian** [comment]
I apologize for the delay on this. This has been implemented in #1115
