### ISSUE TITLE
servers.WaitForStatus timeout does not work as expected

### ISSUE THREAD

**Issue by sb10** [gophercloud/gophercloud#116]
I would expect the purpose of the timeout in WaitForStatus() is that after the timeout period ends, WaitForStatus returns regardless of the status.

However, servers.WaitForStatus() is implemented with gophercloud.WaitFor(), but the latter does not actually interrupt its predicate function after the timeout period. Instead it waits for the predicate to return a value.

Unfortunately it seems that servers.WaitForStatus makes calls that can hang indefinitely in the case of a problem bringing up the server.

**Comment by jtopjian** [comment]
It looks like this is what #83 is implementing, however, it removes the ability for the entire `WaitFor` function to stop after a set amount of time.

I think both forms of a timeout are applicable here, since there are two main cases to account for:

1. The predicate function never returns (network issue, server issue)
2. The satisfied value is never returned.

**Comment by jrperritt** [comment]
closed by #221
