### ISSUE TITLE
API for chunk upload of large objects

### ISSUE THREAD

**Issue by swapnilgm** [gophercloud/gophercloud#1191]
I want to upload the large object to Swift object store using [large object support](https://docs.openstack.org/swift/latest/overview_large_objects.html) for openstack. AFAIK currently Gophercloud SDK supports it using `Create` API with configurable `CreateOpts`. But at the end API user has to himself set data in chunks and do separate `Create` call for each chunk. And at the end user has to upload Manifest object at the end. Feel free to correct me if i'm wrong. Every user has to implement his own logic of parallelly upload chunk and manifest object.

So, Hereby I'm proposing change  add some configuration option like `CreateOpts.ChunkUpload bool` indicating do chunk upload, which will accept reader  of `CreateOpts.Content`. Its implementation will take care of dividing data in chunks and starting parallel go routines for each chunk upload. May be with configurable retry attempts for failed chunk uploads. Or may be make it completely separate API from current Create call, say `MultiPartCreate`.

If this feature is already available, please guide me though the example and API code link. If you are accepting to introduce this feature, i'm ready to implement it.

**Comment by jtopjian** [comment]
Check out this PR (https://github.com/gophercloud/utils/pull/47). I think it has the functionality you're looking for :)

**Comment by lll-phill-lll** [comment]
Is there any alternative way to upload large(>5gb) files to rackspace cloudfiles? As i see pr will be ready not so soon

**Comment by jtopjian** [comment]
> As i see pr will be ready not so soon

You could test and review the PR - that would help accelerate it being merged.

**Comment by lll-phill-lll** [comment]
It seems like in old gophercloud (rackspace/gophercloud) was a branch designed for Rack and there were functions that allowed to upload/download large files (because Rack can work with large files). Why do you need to write this functionality anew, if it is already implemented? If there is an issue I missed notify me but I don't see any. https://github.com/rackspace/gophercloud/blob/rackcli/openstack/objectstorage/v1/objects/requests.go

**Comment by jtopjian** [comment]
It's quite possible it was not brought over to the new Gophercloud repository because it was specific to Rackspace. This repository is for OpenStack proper.

In addition, from scanning the upload functions, it provides very basic large object upload support. The PR I referenced is a full port of the Python client's upload/download functionality which includes compatibility with the python client as well as full support for SLO and DLO upload/download.

If all you need is very basic large object upload support, you should be able to copy/paste the code you referenced into your application with little modification.

**Comment by jtopjian** [comment]
This functionality is now available at https://github.com/gophercloud/utils/tree/master/openstack/objectstorage/v1/objects.
