### ISSUE TITLE
Add organizational unit (OU) support for the manila securityservices

### ISSUE THREAD

**Issue by kayrus** [gophercloud/gophercloud#1334]
New organisational unit field [was introduced](https://bugs.launchpad.net/manila/+bug/1696669) in Manila 2.44 microversion.

[API reference](https://developer.openstack.org/api-ref/shared-file-system/?expanded=update-security-service-detail,create-security-service-detail#create-security-service)

#1315

**Comment by jtopjian** [comment]
@kayrus We'll need to see references to the Manilla service API code that confirms `OU` is a new attribute of the models. See [here](https://github.com/gophercloud/gophercloud/blob/master/docs/contributor-tutorial/step-03-code-hunting.md) for instructions.

The bug report you gave links to various Gerrit patches which is along the same lines of what we're looking for, but if we can pull references from the current codebase, that would be best (who's to say those patches weren't updated since being merged?)

Please let me know if you have any questions.

**Comment by kayrus** [comment]
create the flow goes from https://github.com/openstack/manila/blob/master/manila/api/v1/security_service.py#L210-L211 to https://github.com/openstack/manila/blob/master/manila/db/sqlalchemy/api.py#L3281 where it takes the model and ou is in there https://github.com/openstack/manila/blob/master/manila/db/sqlalchemy/models.py#L896

I hope it is sufficient.

**Comment by kayrus** [comment]
Any chance to review the corresponding PR?

**Comment by jtopjian** [comment]
Implemented in #1315
