### ISSUE TITLE
Add support for Heat/Autoscaling

### ISSUE THREAD

**Issue by xinau** [gophercloud/gophercloud#1446]
It seems like there is no support for Heat/Autoscaling.
If I'm mistaken please point me to the documentation.

**Comment by jtopjian** [comment]
Heat can be found here: https://github.com/gophercloud/gophercloud/tree/master/openstack/orchestration/v1

I'm going to close this issue, but please let me know if you have any other questions.

**Comment by xinau** [comment]
@jtopjian please correct me if I'm mistaken this is the code for heat, but it is missing how to define AutoScaling Resources. https://wiki.openstack.org/wiki/Heat/AutoScaling#The_AutoScaling_Resources

**Comment by zaneb** [comment]
As that wiki page says [right at the top](https://wiki.openstack.org/wiki/Heat/AutoScaling#Note), it contains an obsolete proposal that was never implemented.

There's no need for gophercloud, or any other client, to 'support' Autoscaling resources, or any other type of Heat resources, because Heat resource types are used in the template passed to Heat and don't have separate APIs.

I do notice that the [`signal` API](https://developer.openstack.org/api-ref/orchestration/v1/#send-a-signal-to-a-resource) is not implemented in gophercloud. This is usually used by other OpenStack services (such as Aodh or Monasca) to perform autoscaling, but it can be used by user clients as well. Somebody might find this useful.

**Comment by jtopjian** [comment]
@zaneb Thank you very much for the clarification.
