### ISSUE TITLE
Networking V2: Add MTU extension support

### ISSUE THREAD

**Issue by kayrus** [gophercloud/gophercloud#1493]
Neutron supports MTU extension: https://github.com/openstack/neutron/blob/mitaka-eol/neutron/extensions/netmtu.py

And starting from Pike, MTU extension is writeable: https://github.com/openstack/neutron/blob/stable/pike/neutron/extensions/netmtu_writable.py

@jtopjian I need you suggestion on how to deal with this implementation. Is it required to introduce two extensions? Is it possible just to add an MTU field into the existing Network structure?

**Comment by jtopjian** [comment]
It can all go under one extension. I think this is a case where users will need to be aware if they can update the MTU or not. For example, in Terraform, either the user would just need to be aware that they can't update the MTU. Conditionally triggering a `ForceNew` might be too difficult.

> Is it possible just to add an MTU field into the existing Network structure?

I've thought about this a lot with the other Neutron extensions. At least for now, it's preferable to stick with the extension pattern. While a lot of these extensions are default extensions, since it's possible to selectively disable them, it's best to treat them as distinct entities.

One possible solution might be to create a monolithic struct in `gophercloud/utils` that combines all of the extensions.
