### ISSUE TITLE
Bug of server list API with limit option.

### ISSUE THREAD

**Issue by sirius1024** [gophercloud/gophercloud#1507]
When I was trying to list my VMs on OpenStack, code like this:

```
	allPages, _ := servers.List(client, servers.ListOpts{
		AllTenants: true,
		Status:     "ACTIVE",
		Limit:      1,
	}).AllPages()
```
But it still returns all matched instances of status is ACTIVE. Maybe limit option not work?

**Comment by jtopjian** [comment]
`Limit` is going to limit the amount of servers per-page. Since you're still calling `AllPages`, it'll still cycle through all pages.

Instead of doing `AllPages()`, use `EachPage()`:

```go
err := servers.List(client, servers.ListOpts{...}).EachPage(func(page pagination.Page) (bool, error) {
  server, err := servers.ExtractServer(page)
  return false, nil
})
```

Returning `false` immediately should limit the results to only 1 page. That's just off the top of my head and haven't tested it, though.

**Comment by sirius1024** [comment]
@jtopjian Ohh! Stupid me. Sorry for my fault. Thanks for your reply！
