### ISSUE TITLE
Support to Project Purge

### ISSUE THREAD

**Issue by acca** [gophercloud/gophercloud#1691]
I'm wondering if there is a way to use the ability to recursively purge resources linked to a project when deleting it.

I see the CLI supports the Purge subcommand: https://docs.openstack.org/python-openstackclient/pike/cli/command-objects/project-purge.html but, as far as I know, there are no direct API endpoint for project purge operation in OpenStack.

Would be possibile/acceptable to implement a `project.Purge` method in `gophercloud` that recursively purges all resources, following the same pattern used in the OpenStack CLI ?

**Comment by jtopjian** [comment]
@acca Gophercloud is really for single API calls. If you'd like to put together some kind of purge function, we could probably add it to https://github.com/gophercloud/utils.

**Comment by acca** [comment]
Already done (via multiple gophercloud methods call) for my specific need but I was also modifying the `project` package to propose a PR.
Currently I just created a `projects.Purge` method that clear all the associated resources. since it is not clear to me how the `utils` repo is organised,  if you can give me some guidelines how it would fit in that repo I can fork it and provide a PR.

For example do you think this method could be added inside a new package in: `gophercloud/utils/openstack/identity/v3/projects/`?

**Comment by jtopjian** [comment]
> For example do you think this method could be added inside a new package in: gophercloud/utils/openstack/identity/v3/projects/?

If the method/function only interacts with project API calls, then yes, that will work.

But it looks like this function interacts with other APIs, such as Block Storage, Image, and Nova (according to the docs). So perhaps `gophercloud/utils/openstack/helpers/projectpurge.go` with the function being called `ProjectPurge`.

I'm open to suggestions, though.

**Comment by acca** [comment]
I like your suggestion and I implemented it in such a way. Please have a look at your earliest convenience and let me know your feedbacks: https://github.com/acca/utils/commit/664d7f12853a35f53c7d07022a08b251f2291f5d

It should work properly as it is, but I want to test a little bit more before proposing a PR.

**Comment by jtopjian** [comment]
@acca Nice work! In general, I think this is quite good.

One suggestion I have is that instead of:

```go
helpers.ProjectPurgeAll(computeClient, storageClient, networkClient, projectID)
```

How about

```go
helpers.ProjectPurgeAll(projectID, purgeOpts)
```

Where `purgeOpts` is defined as:

```go
type ProjectPurgeOpts struct {
  ComputePurgeOpts *ComputePurgeOpts
  StoragePurgeOpts *StoragePurgeOpts
  NetworkPurgeOpts *NetworkPurgeOpts
}

type ComputePurgeOpts struct {
  Client *gophercloud.ServiceClient
}

etc
```

There are three benefits to doing this:

1. If someone wants to add support for purging another service, they only have to add fields to `ProjectPurgeOpts` and not add another parameter to the function. This helps retain backwards compatibility.

2. If you need to add extra options for each type of purging, you can add them to the `<Service>PurgeOpts` struct. For example, let's say you want to provide the ability to delete servers only when they are shut off. If a server is active, you want to halt the purge process. So you can have

3. By using `*ComputePurgeOpts` as the field type, you can check if the value is nil and skip purging those resources. This allows someone to selectively purge only Compute and Storage and skip Networking.

```go
type ComputePurgeOpts {
  Client *gophercloud.ServiceClient
  HaltOnActive bool
}
```

(this is a contrived example - I don't know who would want to do this)

Another suggestion is to make the function a little more explicit. Instead of `clearVolumes` have `clearBlockStorageVolumes`. Instead of `clearFloatings`, have `clearNetworkingFloatingIPs`.

Let me know if you have any questions.

**Comment by acca** [comment]
Completely agree an all your suggestion, I'm going to review it. Thanks.
