### ISSUE TITLE
Blockstorage: Add limits extension

### ISSUE THREAD

**Issue by thcdrt** [gophercloud/gophercloud#1702]
Hello,

I opened recently an issue about nova limits call (https://github.com/gophercloud/gophercloud/issues/1697).
Then I found out that the missing information are in another limits call, but in the volume API.

The code for nova limits is at this path: openstack/compute/v2/extensions/limits
But I can't found the equivalence on volume side in https://github.com/gophercloud/gophercloud/tree/master/openstack/blockstorage/extensions.

Are you ok to allow me to add it?

API Documentation: 
[https://docs.openstack.org/api-ref/block-storage/v3/index.html?expanded=show-absolute-limits-for-project-detail#limits-limits](https://docs.openstack.org/api-ref/block-storage/v3/index.html?expanded=show-absolute-limits-for-project-detail#limits-limits).

V2 implementation:
[https://github.com/openstack/cinder/blob/master/cinder/api/v2/limits.py](https://github.com/openstack/cinder/blob/master/cinder/api/v2/limits.py)

V3 implementation:
[https://github.com/openstack/cinder/blob/master/cinder/api/v3/limits.py](https://github.com/openstack/cinder/blob/master/cinder/api/v3/limits.py)

Thanks,
Thomas

**Comment by jtopjian** [comment]
@thcdrt Yes, thank you for offering 🙂 

We have a [contributor tutorial](https://github.com/gophercloud/gophercloud/tree/master/docs/contributor-tutorial) that should help get you going. Note that you'll need to reference more than just the API docs for this.

Please let me know if you need any help or have any questions.

**Comment by thcdrt** [comment]
Hello @jtopjian, sorry but I don't understand what you want me to add.
In the [create an issue tutorial ](https://github.com/gophercloud/gophercloud/blob/master/docs/contributor-tutorial/step-02-issues.md) in the [add a missing call section](https://github.com/gophercloud/gophercloud/blob/master/docs/contributor-tutorial/step-02-issues.md#adding-a-missing-api-call), the [example](https://github.com/gophercloud/gophercloud/issues/715) just add the link of the doc.

Thomas

**Comment by jtopjian** [comment]
@thcdrt Yes, true. 

Most people contributing PRs skip Part 3 and don't mention the actual API service code either in the issue or PR (https://github.com/gophercloud/gophercloud/pull/716). Either is fine, but it's just become habit to always make mention of it.

**Comment by thcdrt** [comment]
@jtopjian  I updated it, is it better ?

**Comment by jtopjian** [comment]
Yes, it's a good start. And to clarify: these links could go either in the issue or in the PR. The only reason I mentioned this topic is because it's simply out of habit when responding to first-time contributors. 🙂 

To expand on the links you gave:

The purpose behind showing the API code is to validate API output. The API docs are meant to be a human-readable form of that, but often fields can be omitted accidentally.

By tracing the code in the code you gave, it leads us to:

* https://github.com/openstack/cinder/blob/master/cinder/api/views/limits.py
* https://github.com/openstack/cinder/blob/master/cinder/api/views/limits.py#L23-L31
* https://github.com/openstack/cinder/blob/master/cinder/api/views/limits.py#L42-L48
* https://github.com/openstack/cinder/blob/master/cinder/api/views/limits.py#L85-L91

Now we can compare the actual key/values in the API communication with the code above. This does two things:

1. Confirms that the feature is a true "vanilla" openstack feature and not something unique to a private cloud.
2. Helps us determine the proper names and types of the struct that will need modeled in the result output.

Let me know if this helps.

**Comment by thcdrt** [comment]
Thank you very much for the clarifications.

I have one last question, where should I put the code ? 
- https://github.com/gophercloud/gophercloud/tree/master/openstack/blockstorage/v2 and https://github.com/gophercloud/gophercloud/tree/master/openstack/blockstorage/v3
- https://github.com/gophercloud/gophercloud/tree/master/openstack/blockstorage/extensions
I saw that the equivalent code for compute is in the [extensions folder](https://github.com/gophercloud/gophercloud/tree/master/openstack/compute/v2/extensions).

Thomas

**Comment by jtopjian** [comment]
The compute extensions directory is strictly for Compute v2/2.1 API calls.

To date, all Block Storage extensions have been compatible with both v2 and v3, which is why they are stored in a versionless `extensions` directory. 

Do you know if there's truly a difference between the v2 and v3 limits API call? Are there different output or different request arguments? If so, this would be a first... I wonder if just adding separate ones to `openstack/blockstorage/vX/limits` would be the most simple solution.

**Comment by TenSt** [comment]
@thcdrt do you still working on this? I need this functionality for our project, so I would be glad to help you with any blockers/issues if you've encountered any. Or it is out of your scope and I can work on it?

**Comment by TenSt** [comment]
@jtopjian @thcdrt I've added PR #2084 which contains everything to close out this issue.

**Comment by jtopjian** [comment]
Implemented in #2084 

@TenSt Thank you very much!

**Comment by thcdrt** [comment]
Thank you @TenSt for the work !
