### ISSUE TITLE
type about createopts of flavor

### ISSUE THREAD

**Issue by rootdeep** [gophercloud/gophercloud#1716]
why the type of Disk and Swap  in CreateOpts  is a pointer not an int  in  package openstack/compute/v2/flavors/requests.go

**Comment by jtopjian** [comment]
This is so someone can pass the value of `0` as a value for these fields.

**Comment by rootdeep** [comment]
@jtopjian  Aha, is it related to follow code section in gophercloud.BuildRequestBody() :

if requiredTag := f.Tag.Get("required"); requiredTag == "true" {
	if zero {
					
		err := ErrMissingInput{}
		err.Argument = f.Name
		return nil, err
	}
}

**Comment by jtopjian** [comment]
Yes, `Disk` is a required field. Since it's required and doesn't have `omitempty`, it would probably work as `int` instead of `*int`. 

It's possible this field used to not be required and then someone made it required without changing `*int` to `int`. But it's probably something we want to keep now.

**Comment by rootdeep** [comment]
@jtopjian  OK, thanks!
