### ISSUE TITLE
question about the code logic in func extractIntoPtr()

### ISSUE THREAD

**Issue by rootdeep** [gophercloud/gophercloud#1755]
The bellow code section is from func extractIntoPtr()  in  gophercloud/result.go

....
case reflect.Struct:   // at line 136 in v0.6.0
		typeOfV := toValue.Type()
		if typeOfV.NumField() > 0 && typeOfV.Field(0).Anonymous {
			for i := 0; i < toValue.NumField(); i++ {
				toField := toValue.Field(i)
				if toField.Kind() == reflect.Struct {
					s := toField.Addr().Interface()
					err = json.NewDecoder(bytes.NewReader(b)).Decode(s)
					if err != nil {
						return err
					}
				}
			}
...

why dose parse the value to  target struct only  when  the  first member of the given struct  is  anonymous?

**Comment by jtopjian** [comment]
That's a good question.

The OpenStack API has included a number of "extensions" over the years. This can be to add additional functionality to an API or for a company/site to add their own logic to a response. 

Let's use the following JSON response as an example: 

https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/servers/testing/fixtures.go#L232

In this response, the following extensions exist:

* availability zone: https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/servers/testing/fixtures.go#L288
* extended status: https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/servers/testing/fixtures.go#L267-L268
* disk config: https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/servers/testing/fixtures.go#L293

One solution is to add these fields to the main `servers.Server` struct, but Gophercloud splits these fields into separate packages: https://github.com/gophercloud/gophercloud/tree/master/openstack/compute/v2/extensions

There are advantages and disadvantages of doing this. A benefit is that Gophercloud makes it possible to support a number of extra fields in an OpenStack response body.

A disadvantage is that it can be unintuitive about how to use them. `ExtractIntoPtr` is one such area.

In order to combine all of these fields into a single struct, we need to make a new struct that is composed of the main `servers.Server` as well as all of the extensions:

https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/servers/testing/requests_test.go#L259-L266

And the way we can extract all of these fields into this new composed struct is with `ExtractIntoPtr`. You can see that in the code above, the struct is composed of anonymous fields - this is where the logic you're asking about comes into play.

Let me know if this helps.

**Comment by rootdeep** [comment]
OK, thanks!
