### ISSUE TITLE
how to set vm password

### ISSUE THREAD

**Issue by randomHHH** [gophercloud/gophercloud#1936]
i want to create server with password  not use key-pair

**Comment by kayrus** [comment]
@randomHHH you can use `UserData` https://github.com/gophercloud/gophercloud/blob/65804fe9b24146be66c170c01caee23013862d88/openstack/compute/v2/servers/requests.go#L163 field with https://cloudinit.readthedocs.io/en/latest/topics/examples.html#including-users-and-groups cloud-init manifest.

**Comment by randomHHH** [comment]
@kayrus thank u,i think it`s a little complex . i solved it use servers.changeAdminPassword

**Comment by jtopjian** [comment]
@randomHHH Just a quick note: the admin password feature needs to be enabled in the OpenStack environment for it to work: https://docs.openstack.org/nova/train/admin/admin-password-injection.html

I'm glad to hear it's working for you because it is more convenient to work with.

@kayrus's method of using cloud-init is more of a cloud-independent way since it can work in any OpenStack environment.
