### ISSUE TITLE
Confused about response fields: servers hypervisor hostname

### ISSUE THREAD

**Issue by jh125486** [gophercloud/gophercloud#1980]
I'm trying to convert an old py2 app to Golang and I encountering some issues with mapping hypervisors hosts to server VMs.

I'm trying to match up a `compute/hypervisor` with the `HostID` field of `compute/server`.
The `HostID` is returning a UUID though, while the `hypervisor` `ID` field is an `int`.

So for that, I assume I am supposed to use the extended details to get the hypervisor?: https://github.com/gophercloud/gophercloud/tree/master/openstack/compute/v2/extensions/extendedserverattributes

Sorry if this a basic issue, and I can submit a PR if it's code I need to write.

**Comment by kayrus** [comment]
@jh125486 yes, you can follow the https://pkg.go.dev/github.com/gophercloud/gophercloud@v0.11.0/openstack/compute/v2/extensions/extendedserverattributes?tab=doc example

**Comment by jh125486** [comment]
I got it working using the extended attributes, but I'm still confused about the `HostID` field.... what is that supposed to represent if the `Hypervisor.ID` is an `int`?

(Sorry that this isn't really related to the `gophercloud` pkg, more of a "WTF were the OpenStack devs trying to do here")

**Comment by jtopjian** [comment]
@jh125486 Yeah, it's a bit confusing 🙂 

There are a few parts to this:

First, a hypervisor ID can be both `int` and `string`, depending on the "microversion" used to query the API. `int` is "legacy" but still widely received since not many users/devs opt-in to querying with a microversion (which is a whole other thing).

Since both `int` and `string` can be returned, we have opted to have our `hypervisors.Hypervisor` struct use `string` and convert `int` to `string` when an integer is used: https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/extensions/hypervisors/results.go#L204-L215

Now there's `HostID`, which is a `string` (but technically not a UUID - just a long string of characters). A `HostID` points to a hypervisor, but it's not a Hypervisor ID. The purpose of a `HostID` is to provide a _user facing_ ID of the hypervisor their instance is hosted on, but without giving away possible sensitive information like what the real ID of the hypervisor is. This way, users can see if two instances of theirs are hosted on the same hypervisor.

So a `HostID` is a user-facing opaque/obfuscated identifier of a hypervisor while the Hypervisor ID is an admin-facing true ID/UUID of the hypervisor itself. 

So how do you match a server to the hypervisor it's hosted on? Not easily. It appears that you have to match the server's extended `HypervisorHostname` with a hypervisor's `HypervisorHostname`. No matching of IDs seems to be possible.

Let me know if this helps.

**Comment by jh125486** [comment]
That helps 100% 👍
