### ISSUE TITLE
Missing Hypervisor ID in JSON

### ISSUE THREAD

**Issue by clementblaise** [gophercloud/gophercloud#2059]
Is there a reason for the ID to be left out of the JSON serialization?

```golang
type Hypervisor struct {
	...
	// ID is the unique ID of the hypervisor.
	ID string `json:"-"`
}
```

I am working a capacity planning application that use the outputted json and it makes it impossible to link a Compute with an Hypervisor.

**Comment by jtopjian** [comment]
The JSON tag of `-` doesn't mean that it's left out of serialization. It allows for this field to be "post-processed" in a custom way in the `UnmarshalJSON` method: https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/extensions/hypervisors/results.go#L204-L215

I hope that helps.

**Comment by clementblaise** [comment]
Right, it does not pose any problems for `UnmarshalJSON` but I don't see how I can handle the marshalling.

Use case is pretty simple, I am listing resources (Computes, Hypervisor, Ports, Networks ...) from Openstack and saving them in a S3 Bucket via a *bytes.Reader that has been encoded in JSON.

An example of a function used to encode the gathered resources:
```golang
func (f *FetchOpenstack) Hypervisor() (data *bytes.Reader, err error) {
	allPages, err := hypervisors.List(f.ComputeClient).AllPages()
	if err != nil {
		return
	}

	allHypervisors, err := hypervisors.ExtractHypervisors(allPages)
	if err != nil {
		return
	}

	allHypervisorsJson, err := json.Marshal(allHypervisors)
	if err != nil {
		return
	}

	return bytes.NewReader(allHypervisorsJson), nil
}
```

Do you see how I can make it work? The only way I can think of is pretty dirty, it would involve rewriting the struct annotation via reflection.

I am a bit surprised that Hypervisor specifically use the annotation `json:"-"` for the ID as all the other resources mentioned use `json:"id"` instead.

**Comment by jtopjian** [comment]
> I am a bit surprised that Hypervisor specifically use the annotation json:"-" for the ID as all the other resources mentioned use json:"id" instead.

This is because the `id` field of this API call switched from an `int` to a `string` without a proper major version increase - essentially causing a backwards incompatible break between OpenStack releases for typed languages like Go.

Because of this, what _would_ have been simple, is now more complicated. I think the best method of proceeding would be to create a local struct that wraps the Hypervisor struct and implement a `MarshalJSON` method on that struct.

**Comment by jtopjian** [comment]
Actually, thinking this through, maybe this deserves having a `MarshalJSON` method added alongside the `UnmarshalJSON` method here. This is something I can look at doing, but it'll take a few days for me to get to. I'd be happy to review a PR, though.

**Comment by clementblaise** [comment]
Ok thank you for the help and the detailed answer.

If such a method could be added, should it be applied to all the other resources as well? And should the implementation use an intermediate struct?

**Comment by jtopjian** [comment]
> If such a method could be added, should it be applied to all the other resources as well? 

Generally no. Most other structs have their own way of marshalling a struct (or at least converting it to a generic map which can then be marshalled into JSON), using an in-house pattern name of `To<something><action>Map`. For example: https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/servers/requests.go#L222-L281

However, for this specific case, because the Hypervisor API is "read-only", there's no "action" being performed and so `MarshalJSON` is the only way to go.

> And should the implementation use an intermediate struct?

Usually there is a temporary/intermediate struct. You can see this within Gophercloud by searching for both `MarshalJSON` and `UnmarshalJSON`.
