### ISSUE TITLE
Network v2 : Missing "binding:" fields

### ISSUE THREAD

**Issue by mdelord** [gophercloud/gophercloud#2082]
In Network v2 API, [/v2.0/ports](https://docs.openstack.org/api-ref/network/v2/index.html?expanded=show-port-details-detail,list-ports-detail#list-ports) returns several fields like `binding:host_id` that are not used in the extraction.

Can we add them in [Port struct](https://github.com/gophercloud/gophercloud/blob/master/openstack/networking/v2/ports/results.go#L61) ?

**Comment by jtopjian** [comment]
The additional Ports fields are all defined as "extensions" in Neutron. Because of this, they have been broken up into different packages. For example, `binding:host_id` is defined here: https://github.com/gophercloud/gophercloud/blob/master/openstack/networking/v2/extensions/portsbinding/results.go

Here's some example code about how to use this with the Ports struct: https://github.com/gophercloud/gophercloud/blob/master/openstack/networking/v2/extensions/portsbinding/testing/requests_test.go#L66-L71

Please let me know if you have any questions.

**Comment by mdelord** [comment]
I didn't see this extension, we will use it, thanks for your answer.
