### ISSUE TITLE
Enhancement: Extend port to add optional value_specs field

### ISSUE THREAD

**Issue by Xenwar** [gophercloud/gophercloud#2180]
When creating resources (network, port, routers and others), I would like to specify additional key/value pairs using ValueSpecs. There was a mention of it in https://github.com/gophercloud/gophercloud/issues/441 a while ago, not quite sure the exact context was though. 

An example can be found here. https://github.com/hashicorp/terraform-provider-openstack/blob/master/openstack/types.go#L163-L173

**Comment by jtopjian** [comment]
@Xenwar The concept of "ValueSpecs" in Terraform is used to add arbitrary key/value pairs that are normally not supported in a "vanilla" OpenStack environment. Gophercloud only supports vanilla/standard OpenStack APIs and so something like ValueSpecs wouldn't be added to Gophercloud itself. However, you can override key methods in Gophercloud in order to add additional fields, which is what the code you've linked to is doing. You can use this same method within your own code that you're developing.

I'm going to close this issue but please let me know if you have any questions.

**Comment by lentzi90** [comment]
Would it be possible to reconsider this?
I opened an [issue in cluster-api-provider-openstack](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1415) for supporting value_specs. The discussion there seems to indicate that it might be possible to add it here now that [it is part of the OpenStack API](https://docs.openstack.org/heat/zed/template_guide/openstack.html#OS::Neutron::Port-prop-value_specs). What do you think?
@jtopjian
