### ISSUE TITLE
Issue when creating/getting/delete objectstorage container/object with special chars like %

### ISSUE THREAD

**Issue by snigle** [gophercloud/gophercloud#2189]
Example : 
```go
containers.Create(client, "test with %", containers.CreateOpts{StoragePolicy: "PCS"}).Err
```
error :"parse \"https://storage.preprod.sbg.cloud.ovh.net/v1/AUTH_639ff29120f5458d92ddc4063ed8374d/test with %\": invalid URL escape \"%\"

Container name and object name are not well encoded in the url.
Preparing a pull request to fix.

**Comment by jtopjian** [comment]
@snigle As of the previous release, you will now have to url encode container names before passing them to Gophercloud functions: https://github.com/gophercloud/gophercloud/blob/master/CHANGELOG.md#0180-june-11-2021

Having Gophercloud do all url encoding was causing issues with other software.

**Comment by snigle** [comment]
Hello did you try to use url.PathEscape instead of QueryEscape ? 
It looks like fixing escape issue with the old code. (That's what my PR did).
Maybe the person who has the previous issue can test on my branch ?

**Comment by jtopjian** [comment]
I don't think `url.PathEscape` was tested. However, I think it's best for Gophercloud to expect that the URL is escaped (one way or another) already. This allows devs to do their own escaping to account for any edge cases in custom clouds.

As I mentioned in the comments here (https://github.com/gophercloud/gophercloud/pull/2160#issuecomment-856999102) I understand this is a breaking change and I apologize.

**Comment by snigle** [comment]
Ok, I don't really agree with "his allows devs to do their own escaping to account for any edge cases in custom clouds"
because if it's true we should remove all url.QueryEscape every where in gophercloud like in instance.Get(client, instances.GetOpts{}) ? 😇 

Nevermind I will patch on the client side for containers and objects stuff, it was just my point of view, you can close the issue 😉 

Thanks for the quick replies 😃

**Comment by jtopjian** [comment]
I understand and respect the disagreement. 

The main issue is that `QueryEscape` was the root cause of an Object Storage issue that did not exist before it was introduced. 

> because if it's true we should remove all url.QueryEscape every where in gophercloud like in instance.Get(client, instances.GetOpts{}) 

There are only two areas in Gophercloud that use `url.QueryEscape`:

```
$ grep -R -l QueryEsc *
openstack/identity/v3/extensions/ec2tokens/requests.go
openstack/identity/v3/extensions/oauth1/requests.go
```

These implementations were copied from the official Python libraries so there's confidence that it won't cause incompatibilities when communicating with the OpenStack Identity service.

Regarding the `Encode` method, which is used in the `params.go` file, this method is very different than `QueryEscape` or `PathEscape`. It is not altering the value of the parameter like `QueryEncode` and `PathEscape`.
