### ISSUE TITLE
The CreateOpts struct no BlockDeviceMapping field

### ISSUE THREAD

**Issue by DeyunLuo** [gophercloud/gophercloud#2210]
In nova-api doc 
[create-server request](https://docs.openstack.org/api-ref/compute/?expanded=create-server-detail#create-server)
has an optional field block_device_mapping_v2 in request body, If specified the block_device_mapping_v2.volume_size field, the instance server system disk will use this field, not flavor.
I think is very useful, gophercloud will add this field?
I have aleady add this fileld to CreateServerOpts and func ToServerCreateMap, if anyone like this, I can have a pr.

**Comment by jtopjian** [comment]
@DeyunLuo This is implemented in https://github.com/gophercloud/gophercloud/tree/master/openstack/compute/v2/extensions/bootfromvolume

Please let me know if that helps.

**Comment by DeyunLuo** [comment]
> @DeyunLuo This is implemented in https://github.com/gophercloud/gophercloud/tree/master/openstack/compute/v2/extensions/bootfromvolume
> 
> Please let me know if that helps.

Oh very thanks, It's very useful.

**Comment by DeyunLuo** [comment]
> @DeyunLuo This is implemented in https://github.com/gophercloud/gophercloud/tree/master/openstack/compute/v2/extensions/bootfromvolume
> 
> Please let me know if that helps.

**Oh, very thanks, It's very useful.**

### I also have two question.

1. How to build CreateOptsExt include `block_device_mapping_v2` field and  `key_name` field, I find `BlockDevice` struct from `openstack/compute/v2/extensions/bootfromvolume/requests.go` and `CreateOptsExt` from `openstack/compute/v2/extensions/keypairs/requests.go`, only can add a custom createOpts like this [Custom request objects](https://github.com/gophercloud/gophercloud/blob/master/docs/FAQ.md)?

**Comment by jtopjian** [comment]
> How to build CreateOptsExt include block_device_mapping_v2 field and key_name field in request body?

See this issue for a detailed explanation (https://github.com/gophercloud/gophercloud/issues/2195) and let me know if you have any questions.

> nova-api can create multiple server, need use the field return_reservation_id in create-multiple-servers-detail, api interface will return a reservation_id, but I didn't find the field in gophercloud source code.

It looks like someone tried adding this field before, but chose to defer the addition until later since it would require a dedicated Extract function on the result: https://github.com/gophercloud/gophercloud/pull/1471

> The above question can find in gophercloud docs?

I usually use the Github search bar to find relevant fields. Since all Gophercloud structs are tagged with the JSON field name, you can either use the Github search bar or use `grep` on the command-line to see if Gophercloud has support for the field:

```bash
$ git clone https://github.com/gophercloud/gophercloud
$ cd gophercloud
$ grep -R block_device_mapping_v2 *
$ grep -R return_reservation_id *
```

> If you have some suggestion about learn how to use gophercloud. Please give me a link, very thanks.

Unfortunately there aren't any tutorials aimed at beginners. However, the [acceptance test suite](https://github.com/gophercloud/gophercloud/tree/master/acceptance/openstack) provides numerous examples of how to use Gophercloud to do different tasks. For example, you can find example code for the `bootfromvolume` extension here:

* https://github.com/gophercloud/gophercloud/blob/9abac83404d86f64e4a8e887afbc5e9c8a315945/acceptance/openstack/compute/v2/bootfromvolume_test.go
* https://github.com/gophercloud/gophercloud/blob/9abac83404d86f64e4a8e887afbc5e9c8a315945/acceptance/openstack/compute/v2/compute.go#L134

> gophercloud also have community like slack group?

Github Issues is the only communication forum for questions, though please feel free to ask as many questions as you'd like.

**Comment by DeyunLuo** [comment]
> > How to build CreateOptsExt include block_device_mapping_v2 field and key_name field in request body?
> 
> See this issue for a detailed explanation (#2195) and let me know if you have any questions.
> 
> > nova-api can create multiple server, need use the field return_reservation_id in create-multiple-servers-detail, api interface will return a reservation_id, but I didn't find the field in gophercloud source code.
> 
> It looks like someone tried adding this field before, but chose to defer the addition until later since it would require a dedicated Extract function on the result: #1471
> 
> > The above question can find in gophercloud docs?
> 
> I usually use the Github search bar to find relevant fields. Since all Gophercloud structs are tagged with the JSON field name, you can either use the Github search bar or use `grep` on the command-line to see if Gophercloud has support for the field:
> 
> ```shell
> $ git clone https://github.com/gophercloud/gophercloud
> $ cd gophercloud
> $ grep -R block_device_mapping_v2 *
> $ grep -R return_reservation_id *
> ```
> 
> > If you have some suggestion about learn how to use gophercloud. Please give me a link, very thanks.
> 
> Unfortunately there aren't any tutorials aimed at beginners. However, the [acceptance test suite](https://github.com/gophercloud/gophercloud/tree/master/acceptance/openstack) provides numerous examples of how to use Gophercloud to do different tasks. For example, you can find example code for the `bootfromvolume` extension here:
> 
> * https://github.com/gophercloud/gophercloud/blob/9abac83404d86f64e4a8e887afbc5e9c8a315945/acceptance/openstack/compute/v2/bootfromvolume_test.go
> * https://github.com/gophercloud/gophercloud/blob/9abac83404d86f64e4a8e887afbc5e9c8a315945/acceptance/openstack/compute/v2/compute.go#L134
> 
> > gophercloud also have community like slack group?
> 
> Github Issues is the only communication forum for questions, though please feel free to ask as many questions as you'd like.

ok, thank you for the answer.
