### ISSUE TITLE
[ANN] New Gophercloud Maintainers

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/gophercloud#2246]
In similar vein to #328, I'm pleased to announce @EmilienM and his team as new maintainers for this repository as well as [gophercloud/utils](https://github.com/gophercloud/utils). They will continue reviewing PRs, addressing issues, and future development. 

I have known Emilien for a good number of years from the OpenStack community and from the work that he and his team have contributed in the past, I'm excited to hand the reigns over to them.

**Comment by pierreprinetti** [comment]
We had our first **and last** internal Red Hat meeting about Gophercloud.
As detailed down below, **further discussions will be public and publicly advertised**.

Attendees: @pierreprinetti @mdbooth @EmilienM @mandre @ericarrakis

## Discussion points:

* This document should be public
* We don’t want Gophercloud to be exclusively Red Hat
* We want to work in the open, maintain an healthy diverse and inclusive community
* No change for us, in our commitment, however will involve more load
* We are inheriting a project in ‘good shape’
* We want to set up a public and publicly advertised discussion space (at least initially, that's a meeting)
* In order to publicly advertise meetings (and other info), we might want to investigate using gophercloud.io
* Umbrella
  * opendev makes your project part of a community. It gives you access to a framework (governance, tools), management and technical infrastructure. On top of, perhaps, a new home for the CI (which is configured in Zuul).
  * in OpenDev, we might leverage the community to tighten the bound between OpenStack and Gophercloud
  * we want to stay on Github for reach reasons
  * shall we get closer to the OpenStack community?
  * we should also consider the Kubernetes-sigs org

## Next steps and Action items:
* (@EmilienM  / @pierreprinetti  - @mandre when back from PTO) reached out to dependent projects. “We are looking to rebuild a healthy governance for Gophercloud. Wanna join?”
* (@EmilienM  / @mdbooth) reach out to opendev and the current CI donors. “We might need a new home for gophercloud (and more stable CI resources).”
* (@pierreprinetti, with @ericarrakis in cc) reach out to RH Legal
* (@EmilienM) Set up weekly 30mins office hours and publish the schedule and the Meet link down below

## Questions for @jtopjian and @jrperritt:
* github.com/gophercloud org ownership?
* who maintains and pays for gophercloud.io? Can we update and add content there?

**Comment by mnaser** [comment]
FWIW, we're heavily reliant on Gophercloud and we've provided resources to @jtopjian in the past for it.  If things don't work out with OpenDev, we're more than happy to provide Zuul resources through our VEXXHOST CI for the project.

**Comment by jtopjian** [comment]
> github.com/gophercloud org ownership?

We've got this sorted out and I can assist with any owner-level changes.

> who maintains and pays for gophercloud.io? Can we update and add content there?

The link on http://gophercloud.io still points to rackspace, so this page/domain are quite old. We're not sure who the owner is, so it's safe to say that this domain isn't usable.

**Comment by EmilienM** [comment]
Starting from today, I'll add @pierreprinetti and @mandre as maintainers so they can help to merge pull requests.
On a side note: I'm preparing a new release for November, stay tuned.

**Comment by DSpeichert** [comment]
> We want to set up a public and publicly advertised discussion space (at least initially, that's a meeting)

Github Discussions is an option that fits the Github workflow very well (as opposed to Gerrit + ML).

**Comment by EmilienM** [comment]
> > We want to set up a public and publicly advertised discussion space (at least initially, that's a meeting)
> 
> Github Discussions is an option that fits the Github workflow very well (as opposed to Gerrit + ML).

Good idea. I've enabled it so people feel free to start new discussions: https://github.com/gophercloud/gophercloud/discussions

**Comment by ozerovandrei** [comment]
Hello.

Sorry for the off-topic but do you have any plans to also maintain https://github.com/terraform-provider-openstack/terraform-provider-openstack in the future?

The reason for my question is that I haven't been using OpenStack for a few years, and I don't have any plans to start again, given that I started work at the cloud provider that doesn't have it.
I still do code-reviews and releases of the provider sometimes but I don't think that I can do it really often.

Sorry for the blunt question but maybe your team can also maintain the provider?

You can reply here or write me an email if you want to discuss it.

**Comment by EmilienM** [comment]
Hey @ozerovandrei , thanks for reaching out.

> Sorry for the off-topic but do you have any plans to also maintain [terraform-provider-openstack](https://github.com/terraform-provider-openstack/terraform-provider-openstack) in the future?
> 
> The reason for my question is that I haven't been using OpenStack for a few years, and I don't have any plans to start again, given that I've just got a new job at the cloud that doesn't have it at all. I still do code-reviews and releases of the provider sometimes but I don't think that I can do it really often.
> 
> Sorry for the blunt question but maybe your team can also maintain the provider?

Several reasons makes me think this is not a great idea in the current state of things but I could be proven wrong and things can evolve of course.

* I don't think any of us has contributed (enough) to the Terraform provider, therefore we probably lack a lot of knowledge to be able to maintain it.
* We're currently "low" in resources for Gophercloud. Not working full time on it, but rather as best effort with the long term goal to release 1.0, then 2.0, improve CI, merge PRs, resolve major issues, scale our community. I don't think we could do a similar effort at the same time with another project (ie Terraform provider). However we can learn from it and maybe later help you.

Have you reached out to the contributors of the Provider? Would they be willing to help as well?

This is not a "no", but rather a "not yet" from my side; as I don't want to commit to something I know we'll not be able to help right now.
