### ISSUE TITLE
req.Close = true in provider_client.go triggers HAProxy TCP RST

### ISSUE THREAD

**Issue by erhudy** [gophercloud/gophercloud#244]
(pinging @kyarovoy on account of his name appearing in the blame output for provider_client.go)

Re-filing this bug from https://github.com/mitchellh/packer/issues/4450, per @rickard-von-essen. `req.Close = true` in provider_client.go (https://github.com/rackspace/gophercloud/blame/c90cb954266e1bdd6d1914678fd6909fc5fabbfa/provider_client.go#L189) interacts strangely with our current HAProxy configuration. It reliably causes both Packer and Terraform to hork out error messages like
```
tcp x.x.x.x:54470->y.y.y.y:8774: read: connection reset by peer.
```

Per the linked Packer issue, testing Packer with this particular line removed from Gophercloud allowed us to get past the connection reset issue.

The HAProxy configuration template in question is available at https://github.com/bloomberg/chef-bcpc/blob/master/cookbooks/bcpc/templates/default/haproxy-head.cfg.erb. HAProxy version is 1.5.18. The problem still occurred with 1.6.x versions of HAProxy.

**Comment by erhudy** [comment]
Things tried in the HAProxy configuration already: disabling `option abortonclose`, disabling `option http-server-close`. Neither change had an effect.

**Comment by jrperritt** [comment]
> req.Close = true in provider_client.go interacts strangely with our current HAProxy configuration

I understand: that line was put there specifically because _not_ having it was interacting strangely for other users ([see here](https://github.com/rackspace/gophercloud/issues/465)). The simplest thing for you to do would be to do what you did: comment out or delete that line in the Packer source code and then rebuild it. 

I've not used HAProxy in many years, so I can't help with its configuration. The line in question basically prevents reuse of connections between requests. Short of a compelling reason to change it (which I'm open to hearing), I'm not sure there's anything to do here.

**Comment by erhudy** [comment]
Forgot all about this bug. Closing the loop on it - the culprit was `option nolinger` in the HAProxy configuration.

**Comment by rickard-von-essen** [comment]
Great that you report back. This might help someone else stumbling on the same thing.
