### ISSUE TITLE
There is no support for Cinder microversions

### ISSUE THREAD

**Issue by j-griffith** [gophercloud/gophercloud#412]
Cinder has adopted microversions and moved to a base version of V3.  Gophercloud should be updated to support this so we can start using shiny new things in Cinder.

**Comment by urzds** [comment]
Was this implemented in #415?

**Comment by jtopjian** [comment]
Yes, I think this issue is closable.

Best practices about microversions are described here: https://github.com/gophercloud/gophercloud/blob/master/docs/MICROVERSIONS.md. Gophercloud's Cinder support has some microversion-enabled features already added.

Please let me know if you have any questions.
