### ISSUE TITLE
Keystone token expired in the middle of a long run API request

### ISSUE THREAD

**Issue by xiangfeiz** [gophercloud/gophercloud#459]
Before starting a PR, please read the [style guide](https://github.com/gophercloud/gophercloud/blob/master/STYLEGUIDE.md).

There are some OpenStack API requests that will invoke other OpenStack API requests to get the job done. For example, a nova volume-detach request will call cinder API to detach the volume. The internal API requests rely on the Keystone token received by the first OpenStack API request from external. The token is valid at the time of the first request from external is processed, but the token may expire in the middle when the internal API requests are processed.

When it happens, the OpenStack objects are in a wrong state. And the external caller won't be able to know it has failed.

There is an config AllowReauth in gophercloud to allow re-authenticate when 401 Unauthorized is received. But it does not help the scenario here because the request from gophercloud to OpenStack returns ok because the token is valid at that time.

I don't know if this can be solved inside OpenStack by switching from token based authentication to trust based authentication (something heat engine uses). But I'd like to propose a solution inside gophercloud.

Add a config to set token expiration time, e.g. 1.5 hours. This should be less than the Keystone token expiration time. The difference is saved for the long run API request to finish all the internal API requests.
Keep track of the time when the keystone token is received.
When setting authentication header, compare the current time with the creation time of the token,  if the duration is larger than the config, request a new token.

**Comment by xiangfeiz** [comment]
The issue reflected in kubernetes: https://github.com/kubernetes/kubernetes/issues/50446

**Comment by jtopjian** [comment]
@xiangfeiz Thanks for reporting this. I'm not familiar with Kubernetes, but I understand what's going on.

`python-keystoneclient` does something like this [already](https://github.com/openstack/python-keystoneclient/blob/1e7543786ec60714a7723eb191bc65c31a42b0aa/keystoneclient/auth/identity/base.py) (search for `reauth`, `min_token`, and `get_access`). 

It's certainly possible for Gophercloud to do this, it's a matter of figuring out the best way to implement it. Thinking out loud:

* Reauthentication is being done [here](https://github.com/gophercloud/gophercloud/blob/50cdddf51c54e8df178af065055cbc5b3cf442e1/provider_client.go#L210)
* A check for early reauthentication would probably best be done somewhere closer to the [start](https://github.com/gophercloud/gophercloud/blob/50cdddf51c54e8df178af065055cbc5b3cf442e1/provider_client.go#L111) of the function. There's probably an element of a bootstrapping/first request scenario to account for.
* For the most flexibility, a new config option should be added around [here](https://github.com/gophercloud/gophercloud/blob/50cdddf51c54e8df178af065055cbc5b3cf442e1/provider_client.go#L69) which would allow setting a minimum timeout in seconds. `keystoneclient` has this hard-coded, but given the variables at play here (arbitrary task execution time and site-specific token longevity), a hard-coded value will only help a finite amount of situations.

@jrperritt thoughts?

**Comment by jrperritt** [comment]
> jrperritt thoughts?

I don't think this is something that Gophercloud should handle. If I understand correctly, it only occurs when a token expires during an OpenStack operation that triggers 1 or more other OpenStack operations internally (ie without returning to Gophercloud). If you find that you're running into this problem a lot, you can handle this in your application.

**Comment by jtopjian** [comment]
That's true, but I think the same argument could be made for reauthentication in general, right? There's also the fact that the Keystone SDK is doing some form of proactive reauthentication, even if it's a hard-coded 120 second window. 

If this is compared to standard reauthentication (at least for the sake of discussion), then we'd have to imagine each application re-implementing reauthentication. That means there would have to be some custom Request function that catches a 401 error and then authenticates. I'd imagine that this would look virtually identical in each implementation. Maybe I am being biased because I am for this feature, but I see the same happening for proactive reauth.

**Comment by jtopjian** [comment]
Another way of looking at this feature is to consider it the reauthentication feature. Instead of reauthenticating based on a 401, reauthentication would happen if the token expiry is within a certain window of time.

I imagine this is what `python-keystoneclient` is actually doing.

**Comment by jrperritt** [comment]
> the same argument could be made for reauthentication in general, right

I think not. An application like Kubernetes that is long-running _will_ need to re-authenticate. Conversely, it could run indefinitely without ever hitting this problem.

Additionally, which operations must be called in a way that may trigger this? As an example, if detaching volumes from Nova is the issue here, there is a `Detach` operation in the volume extensions package that presumably wouldn't hit this issue.

**Comment by jtopjian** [comment]
> As an example, if detaching volumes from Nova is the issue here, there is a Detach operation in the volume extensions package that presumably wouldn't hit this issue.

That's because the `Detach` request will go through Gophercloud's provider `Request` and reauthenticate if the first attempt returned a 401, right?

There are OpenStack actions that trigger other actions behind the scenes. For example: creating a snapshot. Both instance and volume-to-image snapshots involve a call to either Nova or Cinder. Once the resource has been snapshot, they make a call to Glance to perform the upload. This happens without returning to Gophercloud (or the python client). Similar actions happen with Nova and Neutron for network connectivity (Neutron will create ports on behalf of Nova).

I wanted to mention those because it takes the focus away from the application (Kubernetes in this case) and because I have experience with the snapshot frustration.

I was about to make the argument that this is an issue with [OpenStack service coordination](http://lists.openstack.org/pipermail/openstack-dev/2015-December/082750.html) which the client/application has no control over. Having reauthentication become based on a window instead of "`expired == true`" helps the situation (as in: "before you do this long-running process, here's a shiny new token"), but I did some quick research and sure enough:

* https://specs.openstack.org/openstack/nova-specs/specs/pike/approved/use-service-tokens.html
* https://blueprints.launchpad.net/nova/+spec/use-service-tokens-pike
* https://specs.openstack.org/openstack/keystone-specs/specs/keystone/ocata/allow-expired.html

As someone who maintains environments that will not be able to upgrade to Ocata/Pike for a long time, I sympathize with this situation (like I said, I'm biased here :) ). But I am happy to see that the correct solution has been identified and implemented. I think this now becomes more of an issue of the cloud provider either looking to upgrade, backport, or increase token expiry in the meantime.

**Comment by jrperritt** [comment]
> That's because the Detach request will go through Gophercloud's provider Request and reauthenticate if the first attempt returned a 401, right

Right. I'm assuming there that it's just a call to Cinder, and not Nova -> Cinder.

> but I did some quick research and sure enough

Indeed, that was going to be my next argument: if we really want to talk about _where_ this should be implemented, it's in OpenStack. It knows better than both the application and Gophercloud what it's doing. By the same argument you made about all applications having to implement this (which is valid), all OpenStack SDKs shouldn't have to implement it either.

**Comment by jtopjian** [comment]
I think it's safe to close this issue unless you wanted to leave it open for further input?

I do sympathize with the situation at hand. My advice to @xiangfeiz would be to look at implementing the service token features as a long-term solution and increasing token expiry with the Keystone service in the short-term.

**Comment by xiangfeiz** [comment]
Thank you for the thorough discussion here. I agree that the service token feature should be the long term fix for this issue. But increasing token expiry won't solve this issue because no matter how long the expiry time is, the issue still could happen close to the end of the token expiry time.

**Comment by jtopjian** [comment]
@xiangfeiz Right - increasing expiry time won't guarantee a resolution to this problem. It's really a short-term fix. For an environment I work in, we set the token expiry to 8 hours specifically to cover long snapshotting processes. Our reasoning is that if a snapshot takes longer than 8 hours, something else is wrong. By that reasoning, you could gauge how long the longest running process should take and set the expiry to that time.

**Comment by danielzhanghl** [comment]
hi, 
we met this issue also in k8s, and be ware of openstack service toke may fix it((https://specs.openstack.org/openstack/nova-specs/specs/pike/approved/use-service-tokens.html)), bu do we have other solution for this one, in the case of clouder provide don't want to change the openstack configuration?
thanks,

**Comment by xiangfeiz** [comment]
One workaround is to change gophercloud code to re-autehnticate before token expired during Request().

**Comment by danielzhanghl** [comment]
but seems jrperritt don't want to change the official gohpercloud code to adopt the openstack behavior.
xiangfeiz, did you change use the private gophercloud code?

**Comment by xiangfeiz** [comment]
sort of. I added the following to gophercloud/provider_client.go:

```
func (client *ProviderClient) Request(method, url string, options *RequestOpts) (*http.Response, error) {
	var body io.Reader
	var contentType *string

	// Check whether TokenID has expired. If so, invoke re-authentication.
	if client.TokenExpireInSeconds >= 0 && client.TokenID != "" {
		currentTime := time.Now()
		duration := currentTime.Sub(client.TokenCreationTime).Seconds()
		if duration >= float64(client.TokenExpireInSeconds) {
			if client.ReauthFunc != nil {
				client.ReauthFunc()
			}
		}
	}
```
