### ISSUE TITLE
Security group rule for ALL ICMP?

### ISSUE THREAD

**Issue by sb10** [gophercloud/gophercloud#512]
I currently do:

    secgroups.CreateRule(p.computeClient, secgroups.CreateRuleOpts{
			ParentGroupID: group.ID,
			FromPort:      0,
			ToPort:        0,
			IPProtocol:    "ICMP",
			CIDR:          "0.0.0.0/0",
		})

But viewing the result in Horizon it is a port of '0', when I want it to say "Any", which is what it says if I create a rule in Horizon with "ALL ICMP".

How do I specify "ALL ICMP" or "Any" in gophercloud?

**Comment by jtopjian** [comment]
@sb10 `-1` has generally been used for "All ICMP". Can you try using that in both the `FromPort` and `ToPort`?

Let me know if that doesn't work. That means something changed and I'll have to dig into it.

**Comment by sb10** [comment]
Thanks, that works. It would be good if this trick was added to the documentation for CreateRuleOpts  in https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/extensions/secgroups/requests.go , otherwise I don't know how anyone would know to do this?

**Comment by jtopjian** [comment]
This has been fixed in https://github.com/gophercloud/gophercloud/pull/513

A little bit of background: before Neutron existed, the Nova Security Group API (`compute/v2/extensions/secgroups` here) interacted with the nova-network security groups. All documentation for security groups was in reference to this API and `-1` was liberally mentioned as it was a common question. 

When Neutron was released, this API acted as a "proxy" API. If Nova was configured to use Neutron, this API would proxy to Neutron and create security groups. If Nova was still configured to use nova-network, behavior was unchanged.

This API was deprecated last year and will now no longer work in the latest release of OpenStack. It's recommended to move to the Networking Security Group API. 

During the deprecation phase, OpenStack documentation changed to cover the Networking resources (ie the `neutron` command) and thus mention of -1 was phased out of existence.

As an aside: to allow all ICMP types with the Networking API, either do not include the minimum and maximum port ranges or specify 0 for both. 

I'm going to close this issue, but let me know if you have any other questions.
