### ISSUE TITLE
Tests fail for go test ./...

### ISSUE THREAD

**Issue by ss22ever** [gophercloud/gophercloud#530]
While installing gophercloud on Ubuntu VM a few tests failed.I would like other contributors to have a look at this
Providing the error log gist:
https://gist.github.com/ss22ever/b9f11a18de3754a163e294656b9c1577/

**Comment by jtopjian** [comment]
@ss22ever Thanks for reporting this. 

The reason why this error was never discovered before is because we only test things in the `testing` packages:

* https://github.com/gophercloud/gophercloud/blob/master/script/unittest
* https://github.com/gophercloud/gophercloud/blob/master/script/coverage

This seems to be a mistake in the [`orchestration/v1/stacks`](https://github.com/gophercloud/gophercloud/tree/master/openstack/orchestration/v1/stacks) package. There shouldn't be any `*_test.go` files in that package. However, I'm not familiar enough with the orchestration stuff to know if those test files are needed or not.


@jrperritt thoughts?

**Comment by ss22ever** [comment]
Ohk @jtopjian @jrperritt  if this looks like a low hanging fruit I would like to fix that.

**Comment by jtopjian** [comment]
@ss22ever You're more than welcome to fix this up.

IMO, the best way to proceed is to move the tests contained in the `*_test.go` files into the `testing` directory/subpackage. Once that's done, the tests will still fail (but at least Travis will now acknowledge them). If you have any problems trying to get the test working, let me know.

**Comment by ss22ever** [comment]
@jtopjian doing that shows :      
can't load package: package github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks/testing: found packages testing (doc.go) and stacks (environment_test.go) in /home/suramya/go/src/github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks/testing

**Comment by jtopjian** [comment]
@ss22ever You'll have to change the package declaration at the top of the `*_test.go` files after you move them. There's probably other modifications you'll have to make within the files as they will be accessing functions outside of the `testing` package.

**Comment by jtopjian** [comment]
I'm going to consider this issue resolved.

The orchestration tests were fixed up a few days ago (#707) and all unit tests are now passing. There are some orchestration tests that should be moved to a "testing" directory, but it might require some effort (or maybe it's easy - I haven't looked into them in too much detail).

But the important thing is that all tests are passing.
