### ISSUE TITLE
Create a new repo for http://gophercloud.io/

### ISSUE THREAD

**Issue by ss22ever** [gophercloud/gophercloud#531]
Currently, http://gophercloud.io/ uses the branch https://github.com/rackspace/gophercloud/tree/gh-pages.Since we have moved to https://github.com/gophercloud/ it will be nice to have a seperate repo for the same.

**Comment by ss22ever** [comment]
@jrperritt Yeah, thanks, I will.Regarding  http://gophercloud.io/ what about all the links on the website that point to rackspace repository?

**Comment by jrperritt** [comment]
I think `gophercloud.io` will stay as-is for now (though I don't control that domain). It's likely that many people still use the `rackspace/gophercloud` library. Regardless of that, all the supported (official) documentation for this repo will reside in this repo so that it can be viewed on Godoc and/or Github.

**Comment by jrperritt** [comment]
closing this as resolved
