### ISSUE TITLE
Compute v2: Add resetNetwork Action

### ISSUE THREAD

**Issue by bugosiphionah** [gophercloud/gophercloud#535]
Nova supports the ability to Reset Networking On A Server.

    https://developer.openstack.org/api-ref/compute/#reset-networking-on-a-server-resetnetwork-action

I can open a PR for this if it is agreed this action is worth implementing.

**Comment by jtopjian** [comment]
@bugosiphionah One difficulty I see with this is:

> Only the XenServer driver implements this feature and only if the guest has the XenAPI agent in the targeted server.

So in order to fully test this, someone will need access to a Xen-based OpenStack environment with instances that have the XenAPI agent running. If you have access to a Xen-based OpenStack environment, you can definitely proceed with a PR.  But if you don't, it would be better to wait until someone with knowledge of running Xen can either add this support or verify the functionality.

**Comment by bugosiphionah** [comment]
I do not have a Xen-based OpenStack environment for now(I may look into this in the near future). Someone knowledgeable can help with adding support for this functionality.
