### ISSUE TITLE
Question on license attribution for OpenStack documentation

### ISSUE THREAD

**Issue by davidaah** [gophercloud/gophercloud#537]
This came up (and was mitigated in the particular case) in #529, however there are cases in the library where examples, etc have already been pulled directly out of the documentation. 

Opening this issue to start a discussion on how the Gophercloud project wants to/should attribute these references under the requirements of CC BY 3.0  (from docs.openstack.org: `Except where otherwise noted, this document is licensed under Creative Commons Attribution 3.0 License. See all OpenStack Legal Documents.`)

**Comment by jtopjian** [comment]
Thanks for opening this for discussion.

I think there are two items for consideration here:

1. The use of API reference samples for unit tests.

I think we should begin to discourage the use of these. Given we don't allow the API reference docs as a primary source of information, we should also not use the API reference samples to base unit tests on. I'm sure there are existing fixtures that are doing this (I've probably done it myself), so we should clean these up.  When I've had an opportunity, I've begun cleaning up fixtures by placing them in a dedicated `const` instead of inline of the mocked HTTP request. Continuing to do this can make it easy to spot and fix these.

Additionally, for incoming PRs, we should request that API fixtures are created as a `const` and not inline, then check and see if they were pulled from the API reference docs.

Even though there are unattributed API samples floating around, I'm willing to say this is a low-ish priority, possibly a Help Wanted, type of task. The reason I think this is lower priority is because I think there's enough good faith here that everyone (notably the Foundation) would understand that the API samples are unattributed out of accident and not intentionally breaking license terms, and that we have a plan to fix this.

2. Situations when there really needs to be an attribution.

I Am Not A Lawyer, so I'm not sure how to best handle this.

To be clear, I fully respect open source licenses and will cooperate with whatever requirements are necessary for attributes.

Placing attribution as a comment above the source code/doc is kind of ugly, but it's the simplest way of handling this. Having a separate doc with line references mapping to attributed code is rather high-maintenance.

If we were absolutely positive that the only attributed references would be from the OpenStack projects, we could probably get away with a global attribution in the README or main GoDoc file, but that's not a situation we can be absolutely sure of.

So I think placing attribution as a comment header above the piece of code/doc is the best way to go.

There's also the situation of someone submitting code which is unattributed. Having a code reviewer ensure that all code is properly attributed is unrealistic. Maybe we should add something to the contributing doc or the Github Issue/PR templates to make sure that all outside code is attributed correctly.

@jrperritt thoughts?

**Comment by jrperritt** [comment]
@jtopjian That's what I'm thinking, too: OpenStack source code (including for unit tests, docs) shouldn't make it's way into this repo, and anything that already is should be removed/changed. Bottom line: We shouldn't be mixing licenses (Gophercloud is under Apache 2.0), nor have the need to provide attributions.

**Comment by jtopjian** [comment]
I'm going to go ahead and close this. We've been doing an okay job with this.
