### ISSUE TITLE
Volume V3: Support Required

### ISSUE THREAD

**Issue by TommyLike** [gophercloud/gophercloud#618]
As the V2 [APIs](https://developer.openstack.org/api-ref/block-storage/v2/) are marked deprecated, is there any plan to support Volume V3 API?

**Comment by jtopjian** [comment]
@TommyLike Yes, support for v3 is in progress.

There are a few issues/PRs already opened for v3 support:

https://github.com/gophercloud/gophercloud/issues/305
https://github.com/gophercloud/gophercloud/issues/412
https://github.com/gophercloud/gophercloud/pull/415

Because of the already opened issues, I am going to close this one, but please let me know if you have any questions.

**Comment by TommyLike** [comment]
Oh, @jtopjian don't need to, thanks!
