### ISSUE TITLE
Avoid caching API responses by HTTP proxies/caches along the way

### ISSUE THREAD

**Issue by freddebacker** [gophercloud/gophercloud#727]
I ran into an issue where I was using terraform-openstack-provider (which uses gophercloud) through an HTTP proxy. Terraform was creating resources in an openstack cloud. Since creating the resources took some time, the initial response from openstack was "still creating...". Further polling of the resource status resulted in receiving cached copies of "still creating..." until time-out.

One could argue this is an openstack issue not including proper cache-control headers in the response, but being explit on the request shouldn't hurt... Especially because gophercloud is meant to query API's which responses are volatile in nature.

**Comment by freddebacker** [comment]
PR #726

**Comment by jtopjian** [comment]
@freddebacker I did a cursory scan and it doesn't look like any of the python client SDKs implement the no-cache header. Is that incorrect?

Either way, I believe this is more of an application-specific problem rather than something that should be fixed in Gophercloud. I understand your reasoning for submitting it here, but if we merge #726 we are dictating to everyone that caching will be disabled, end of story.

However, at the application level, which is user-facing, we can create a option for users to toggle this on and off, which makes more sense to me.

In Terraform, this toggle would be added as a provider-level option/attribute and the value would make its way here:

https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/types.go#L36

Let me know if you have any questions or would like to discuss this further.

**Comment by freddebacker** [comment]
I understand, but I'm not willing to start a "fight" convincing people what would be the best place to fix this...
I saved myself a lot of trouble implementing this in Gophercloud and I thought giving this back to the community. But Gophercloud isn't my project, so you can do with this fix as you see fit...

I do hope however that somehow google search picks up this caching problem so it can help other people; and maybe, someday, someone will fix it in the right place...

One last, thought: Would there be any situation where caching of Gophercloud calls would be beneficial? If not, then there's no reason not to do it; but here's one why you might consider it...

No hard feelings if you reject this all together...

Regards,
Fred

**Comment by freddebacker** [comment]
Hi @jtopjian ,

No offenses taken, don't worry...

I admit, this probably isn't the best place to fix it, but in my opinion neither is Terraform; but in my defense; it was the only/easiest place under my control to fix it myself.

To be honest, I think this is an Openstack bug. In my opinion, the Openstack API (Nova in this case, but equally valid for all other APIs) should include proper HTTP headers in the response to either disallow the caching or at least limit the validity of the answer; given that they describe the current state of an object which isn't permanent. They could do so using any of the techniques described in [the HTTP caching RFC section 5](https://tools.ietf.org/html/rfc7234#section-5).
Still according [the HTTP caching RFC section 4.2.2](https://tools.ietf.org/html/rfc7234#section-4.2.2), in absence of all headers describing the lifetime of the response, heuristic algorithms may be applied... Who knows what is implemented out there... 

Regards,
Fred

**Comment by dklyle** [comment]
@freddebacker It is possible to create an issue in launchpad and attach multiple projects to it. The other place such things were handled in openstack is http://git.openstack.org/cgit/openstack/openstack-specs, but that has mostly been retired and entails significant overhead. The other place one could raise it is with the API Working Group, https://wiki.openstack.org/wiki/API_Working_Group#Communication via the openstack-dev mailing list or just to the mailing list in general. None are ideal, but if you wanted to at least raise the issue in OpenStack, those are some way, mailing list being the least onerous.

**Comment by freddebacker** [comment]
Thanks @dklyle for your suggestions.

Raised to the openstack-dev mailing list here: [http://lists.openstack.org/pipermail/openstack-dev/2018-February/126975.html](http://lists.openstack.org/pipermail/openstack-dev/2018-February/126975.html)

**Comment by cdent** [comment]
It _is_ an OpenStack bug, and bugs should be created. It's been fixed in [placement](http://specs.openstack.org/openstack/nova-specs/specs/queens/approved/placement-cache-headers.html) but it's definitely a problem lots of other places. Having a real bug created about the problem should help to ensure it gets addressed for real.

Wearing my api-sig hat: this isn't something we've really addressed in the past because since the problem was so widespread it felt insurmountable (we could create yet _another_ guidelines no one would follow). If we can point to a real bug that can help, a lot.

**Comment by freddebacker** [comment]
Hi @cdent,

Being relatively new to openstack, someone helping me identifying "lots of other places" and where/how to raise bugs would help... I can definitely see what you mean with "widespread" and "insurmountable".

Feel free to let me know how I can help to get this going in the good direction for the benefit of everyone.

Fred

**Comment by jtopjian** [comment]
@freddebacker You can create a bug report for Nova here:

https://bugs.launchpad.net/nova

I think the way you have described the issue both here and on the OpenStack list is perfect. You could probably either copy/paste or write a similarly-worded bug report.

**Comment by freddebacker** [comment]
Nova bug created: https://bugs.launchpad.net/nova/+bug/1747935

**Comment by jrperritt** [comment]
@freddebacker thank you for filing the bug. It looks like it's going to be fixed upstream in OpenStack.

**Comment by freddebacker** [comment]
Not sure I agree with your conclusion. From what I see from the LP bug, it is not moving anywhere... Besides it will probably take ages to get it fixed.

I'm still wondering if it wouldn't be an opportunity to apply this fix here until it is properly fixed in openstack...

Anyway... I feel like I did everything within my power to raise attention and help the community... Pity nothing is changing...

**Comment by cdent** [comment]
Things do indeed move very slowly in OpenStack, and even when they do move quickly, it unlikely that a fix like this would get universal acclaim to be backported to older versions, thus having workaround in gophercloud may be warranted if gophercloud is going to support older versions (which would make sense since older versions are what is deployed).

Fred, your efforts did cause a bit of progress. I'm adding guidance to the api-sig guidelines on how services _must_ protect against this behaviour: https://review.openstack.org/#/c/550468/

So thanks very much for that, and m apologies that it doesn't move more quickly.

**Comment by jtopjian** [comment]
> Thus having workaround in gophercloud may be warranted if gophercloud is going to support older versions (which would make sense since older versions are what is deployed).

Gophercloud allows applications which consume it to add any additional headers to the http client. Because of this, I think it would be better to add this kind of support in the Gophercloud-based application.

I've mentioned that I would be happy to add this support to Terraform. I keep forgetting about this issue, though, so I've quickly made a Terraform issue about this:

https://github.com/terraform-providers/terraform-provider-openstack/issues/264
