### ISSUE TITLE
Networking V2: Network object lacks many fields returned by get()

### ISSUE THREAD

**Issue by alvaroaleman** [gophercloud/gophercloud#749]
The `type Network struct` is missing [a lot of the fields returned by get requests](https://developer.openstack.org/api-ref/network/v2/#show-network-details)

**Comment by jtopjian** [comment]
@alvaroaleman Thanks for reporting this.

A lot of these fields might be extensions to Neutron and not part of the core "network" struct. An example of this is `segments`. Although it's listed as a response field in the API docs, it's actually an extension to Neutron and is defined in Gophercloud [here](https://github.com/gophercloud/gophercloud/blob/master/openstack/networking/v2/extensions/provider/requests.go).

This is why we need to see links to actual Neutron Python code - we need to determine if it's a core field or an extension.

Using `segments` as an example again, you can see the types of links we're looking for in https://github.com/gophercloud/gophercloud/pull/302

**Comment by alvaroaleman** [comment]
@jtopjian Thanks for the explanation! So the point of forcing the uses to build their own structs if they want attributes that come from an extension is to make them aware that those attributes may or may not be present?

**Comment by jtopjian** [comment]
@alvaroaleman Yes.

Gophercloud attempts to model the OpenStack API's as they are defined in the service code. This includes making explicit distinction between fields that are in a "core" API and what's an extension. One reason for doing this is because OpenStack environments can vary from cloud/vendor to cloud/vendor.  

They key here is to think of the role "developer" when you say "user". Gophercloud is rarely user-facing. A developer of an application or a library/package which sites between Gophercloud will be the one handling the combination of fields. For the combination of fields in vanilla OpenStack environments, it might make sense to one day build a "common" struct. But even if such a struct existed, we still need to break out the individual extensions.

**Comment by alvaroaleman** [comment]
Thanks for the clarification!
