### ISSUE TITLE
rackspace support

### ISSUE THREAD

**Issue by eugenetaranov** [gophercloud/gophercloud#829]
Hello,

I am currently trying to make terraform openstack provider work with rackspace, it requires some changes to be done in gophercloud sources. I would like to know whether it would be possible to get it merged into gophercloud upstream to avoid maintaining a separate fork? 

Here is a sample change for trove https://github.com/eugenetaranov/terraform-provider-openstack/commit/3f816e9dd025a9ac4fdbc69e9ed6581055d6599e. While vanilla openstack endpoints may remain a default, passing additional parameter could switch to RS endpoints..

Let me please know your thoughts.

**Comment by jtopjian** [comment]
@eugenetaranov The effort to get the Terraform OpenStack provider working with Rackspace is definitely appreciated. However, I think you'll end up running into enough small bugs that a separate provider would make sense in the long run. I might be wrong about this, though -- I'll let @jrperritt confirm.

@jrperritt had a partial implementation of a Rackspace provider: https://github.com/hashicorp/terraform/pull/1438

So I think the best long-term solution would be a separate provider. This is already being done with OpenTelekomCloud: https://github.com/terraform-providers/terraform-provider-opentelekomcloud (note the Gophercloud used in this provider is a forked Gophercloud - the import statements are showing `github.com/gophercloud/gophercloud` but that's only because of confusing Go/vendoring limitations.

It would be nice if Terraform plugins could add additional resources to core providers - that way a plugin could act as an overlay - but that's not possible. :/

**Comment by jrperritt** [comment]
It sounds like there are 2 separate questions here:

1. Should changes be added to this repo to allow the library to work with Rackspace?

I think this will be a "no"; the old `gophercloud` repo at `github.com/rackspace/gophercloud` did this. This repo is specifically for OpenStack proper.

2. What effort would be required to support Rackspace externally.

There are 2 possibilities here: Rackspace private cloud and Rackspace public cloud.
Rackspace private cloud should be almost entirely (if not entirely) OpenStack proper, which means a user could use this repo, and it should just work.
For Rackspace public cloud, I agree with @jtopjian : I think a separate provider (read: external repo) would be most reasonable. I'm not sure what the effort level would be (as in, I don't know what the diff is between Rackspace public cloud and OpenStack proper). I'd expect it to vary service to service.

**Comment by eugenetaranov** [comment]
Thanks @jtopjian and @jrperritt for detailed responses, it all makes sense so let's go with separate provider then.
