### ISSUE TITLE
Octavia: support L7 policy/rule operations

### ISSUE THREAD

**Issue by lingxiankong** [gophercloud/gophercloud#832]
Please refer to: https://docs.openstack.org/octavia/latest/user/guides/l7.html

---
- [x] l7 policy create
- [x] l7 policy list
- [x] l7 policy get
- [x] l7 policy update
- [x] l7 policy delete

---
- [x] l7 rule create
- [x] l7 rule list
- [x] l7 rule get
- [x] l7 rule update
- [x] l7 rule delete

**Comment by jtopjian** [comment]
@lingxiankong Thanks for noting this :)

I see the L7 stuff defined here:

https://github.com/openstack/octavia/blob/master/octavia/api/v2/controllers/l7rule.py
https://github.com/openstack/octavia/blob/master/octavia/api/v2/controllers/l7policy.py

But I also see it in the Neutron LBaaS code:

https://github.com/openstack/neutron-lbaas/search?q=l7

Does this mean that L7 is supported in both Octavia and the "deprecated" Neutron LBaaS? Or does Octavia use the `neutron-lbaas` library? Put another way: Does one need to have Octavia deployed to use L7?

The reason I ask is because, given my comment earlier today (https://github.com/gophercloud/gophercloud/pull/831#issuecomment-373191686), I'm wondering if:

1. Similar to LBs, pools, monitors, etc, L7 is supported by both Neutron LBaaS and Octavia. In which case this implementation can go under the current `lbaas_v2` package with no special conditions/checks.
2. We should add it to `lbaas_v2` but with the same kind of service check implemented in #831.
3. Copy/paste `lbaas_v2` to something like `lbaas_v2_octavia` or `lbaas_v2_neutron` or similar and add the L7 stuff to whichever is deemed the current LBaaS v2 API implementation.

I apologize if I'm making this more difficult than it really is.

**Comment by lingxiankong** [comment]
hi, @jtopjian 

AFAIK, the octavia l7 functionality is totally back-compatible with neutron-lbaas, octavia just has more features than the deprecated neutron-lbaas. I was a developer in octavia, btw.

**Comment by lingxiankong** [comment]
@jtopjian if you don't mind, i can hand up to help with this issue.

**Comment by jtopjian** [comment]
> if you don't mind, i can hand up to help with this issue.

We'd love to get your help on this, whether answering questions, implementing the code, or both 😄 

> AFAIK, the octavia l7 functionality is totally back-compatible with neutron-lbaas, 

OK, that's good to know. So implementing this should be quite simple: it'll go in the `lbaas_v2` package and either the `network` or `load-balancer` can use it.

> octavia just has more features than the deprecated neutron-lbaas. 

Right, and this is what I'm trying to sort out.

We've been able to introduce Octavia support into Gophercloud by re-using current [Neutron LBaaS v2](https://github.com/gophercloud/gophercloud/tree/master/openstack/networking/v2/extensions/lbaas_v2) package. This has worked very well so far.

But #831 introduced a feature that is only available in Octavia and not Neutron LBaaS. 

Thinking long-term, I'm wondering if there will be enough Octavia-only features that warrant a dedicated octavia/lbaas_v2 package. Kind of like if Octavia-lbaasv2 was really a v3 API release. 

But if L7 works with both neutron and octavia, then that decision doesn't need to be made here. :)

**Comment by jtopjian** [comment]
> and it's safe for us to add more features and new api supports in lbaas_v2 repo without breaking the current implemented apis

This is a kind of problem we've run into before. Rather than a v3 API, the Octavia enhancements sound similar to a microversion increase (if you think of the `load-balancer` client like a microversion increase). #441 lays out the difficulty in implementing microversion enhancements to existing APIs.

I'm sure that most Octavia-only features can be added to the existing `lbaas_v2` package without any issue at all (as you say, we can simply document these additions), but there might be some future ones that will cause us to rethink the way they're implemented. These future cases are the ones I'm concerned about.

**Comment by jrperritt** [comment]
@jtopjian what do you think about having a top-level `loadbalancer` package, and delegating calls in it to `lbass_v2` unless a change is needed?

**Comment by jtopjian** [comment]
I see similarity between lbaasv2/Octavia and microversions and I think it'll be interesting to keep an eye on this to see if it presents a solution we haven't thought of. I'm kind of hoping some serendipitous solution pops up that we're all in awe over :)

Until then, I think we can proceed as normal and just be mindful.

**Comment by jrperritt** [comment]
This seems different to me. It sounds like microversions are [potentially-backwards-incompatible] changes to a service. Octavia isn't a part of the networking service; it's a service of its own. It seems odd to call a subpackage of `networking` to call load balancer operations when a dedicated service exists for it.

**Comment by jtopjian** [comment]
I agree. The reason I am comparing it to a microversion is because I'm anticipating a backwards incompatible change (and by backwards incompatible I mean a more Go-ish breaking change such as the removal of a request body parameter or something like that). So at the moment the two situations are a bit different. My spidey sense is being cautious, though.

> It seems odd to call a subpackage of networking to call load balancer operations when a dedicated service exists for it.

Agreed. On one hand we get a big win by piggybacking off of the existing `lbaas_v2` package, but yes, this could/should be a first-class service peer of `networking`.

**Comment by jtopjian** [comment]
> It seems odd to call a subpackage of networking to call load balancer operations when a dedicated service exists for it.

I should also mention that if we did make a new first-class `loadbalancer` service directory/package, then problem solved. Octavia-only features would be added there and missing LBaaS v2 features would go in both `networking/v2/extensions/lbaas_v2` and `loadbalancer/lbaas_v2`. 

The problems I'm anticipating all stem from implementing the LBaaS v2 API in a single place.

**Comment by jrperritt** [comment]
Right, I'm suggesting a new top-level `loadbalancer` package to be implemented as you've described.

**Comment by jtopjian** [comment]
Sounds like `loadbalancer/v2/lbaas` (or whichever directory structure is best) it is then 😄

**Comment by lingxiankong** [comment]
hi, @jtopjian this issue could be closed :-) I will submit follow up patches for improvement or potential bugfix, thanks a lot for your review so far!

**Comment by jtopjian** [comment]
Sounds good!

As well, thank you for your work implementing this -- it's very much appreciated!

🎉
