### ISSUE TITLE
advice on error handling

### ISSUE THREAD

**Issue by majewsky** [gophercloud/gophercloud#939]
When I get an error from Gophercloud because (for instance) the server returned 404, the error message is hard-coded to `Resource not found` which is extremely vague. The server usually includes a more helpful error message in the response body, but I have to jump through some hoops to actually get to it, like in

https://github.com/sapcc/limes/blob/46c2e6e6f2aad33b6a0027d698853c7c5f4ad781/pkg/api/token.go#L89-L112

Is this really how this is intended to work or am I missing something?

**Comment by jtopjian** [comment]
It's working as it's coded but I agree that it's not helpful. We recently merged https://github.com/gophercloud/gophercloud/pull/714 so if something similar could be done with the 404, I'd be happy to merge that, too.

**Comment by majewsky** [comment]
The same thing already exists for 404 (if you look in the diff on #714, it's right below the added lines in each file). I think my problem is more that I do not understand the purpose of having all these error types in the first place. What's the benefit of having `ErrDefaultNNN` for each status code instead of just `ErrUnexpectedResponseCode` which already has the `Actual` field to indicate the status code?

**Comment by jtopjian** [comment]
> The same thing already exists for 404

The 403 and 404 errors are now implemented the same way. However, the default error string in the 403 now returns more information about the error than what it did prior to merging #714:

```go
func (e ErrDefault403) Error() string {
	e.DefaultErrString = fmt.Sprintf(
		"Request forbidden: [%s %s], error message: %s",
		e.Method, e.URL, e.Body,
	)
	return e.choseErrString()
}
func (e ErrDefault404) Error() string {
	return "Resource not found"
}
```

Since you mentioned the standard hard-coded `Resource not found` message that 404 is returning, I thought that was what the original issue was about.

> I think my problem is more that I do not understand the purpose of having all these error types in the first place.

Creating types for each class of error can be used to easily compare error responses. For example:

```go
func WaitForRouterToDelete(client *gophercloud.ServiceClient, routerID string, secs int) error {
  return gophercloud.WaitFor(secs, func() (bool, error) {
    _, err := routers.Get(client, routerID).Extract()
    if err != nil {
      if _, ok := err.(gophercloud.ErrDefault404); ok {
        return true, nil
      }

      return false, err
    }

    return false, nil
  })
}
```

I'm sure you could do the same thing by comparing the integer return code, but my understanding is that it's more "Go-ish" to create a type of error for comparison rather than compare an attribute about the error.

If I'm, again, missing the mark with your concern with errors, I apologize.

**Comment by majewsky** [comment]
I see, thanks for clarifying. For perspective, I'm using a slightly different pattern in [Schwift](https://github.com/majewsky/schwift): It also has an `UnexpectedStatusCodeError`, but then uses a special function (rather than subtypes) for checking specific status codes: https://github.com/majewsky/schwift/blob/d23b4052c0866698b14ac13ac98581d9f5440a9b/errors.go#L116-L134 - This avoids most of the ugliness that is mentioned in my initial comment.
