### ISSUE TITLE
Question: Should We Support Additional Filters for LIST APIs in Identity V3 ?

### ISSUE THREAD

**Issue by zhangzujian** [gophercloud/gophercloud#978]
In Identity V3, **LIST** APIs support filters like **name_contains=STR**. If the filter is added into query parameters, the server will return a list of resources of which the names contain **STR**.

This feature is really useful, I think. Should we support it ?

Python source code:
https://github.com/openstack/keystone/blob/master/keystone/common/controller.py#L421

**Comment by jtopjian** [comment]
This does seem useful. Unfortunately it looks like it doesn't work on Extra properties, though, which is disappointing. Otherwise you could do a query such as:

```
http://localhost:5000/v3/projects?email__contains=foo
```

So it seems filters only work on certain fields.

Given that, though, I think this is something we could/should implement. Perhaps adding the following to `ListOpts`:

```go
Filter map[string]string `q:"-"`
```

You would then iterate over the map and append the key/values to the URL during the `ToXListQuery` method.

The reason I think we should use `map[string]string` is because there are far too many combinations of filters to create a structured type with.

Thoughts?

**Comment by zhangzujian** [comment]
@jtopjian Agreed.

**Comment by jtopjian** [comment]
@zhangzujian I wasn't sure if everything was finished here.

Thank you very much for implementing this!
